var car = "subaru";
console.log("Is car == 'subaru'? is predict true? ");
console.log(car == "subaru");
console.log("Is car == 'mercedes benz'? is predict false? ");
console.log(car == "mercedes benz");
var book = "Atomic Habbits";
console.log("is book == 'Atomic Habbits'? Is predict true? ");
console.log(book == "Atomic Habbits");
console.log("Is book == 'fairytale' ? is preidict false?");
console.log(book == "fairytale");
var name = "AQSA";
console.log("is name == 'AQSA' is preidict true?");
console.log(name == "AQSA");
console.log("is name == 'MAHEEN' is predict false ?");
console.log(name == "MAHEEN");
var song = "country road take me home";
console.log("Is song == 'country road take me home' is preidict true ?");
console.log(song == "country road take me home");
console.log("Is song == 'old town road' is predict false ?");
console.log(song == "old town road");
var artist = "BILLIE EILISH";
console.log("is artist == 'BILLIE EILISH' ? is predict true?");
console.log(artist == "BILLIE EILISH");
console.log("is artist == 'LANA DEL REY' ? is predict true?");
console.log(artist == "LANA DEL REY");
